### ISSUE TITLE
New file naming convention/build process automatization

### ISSUE THREAD

**Issue by krzysztofkuczek** [krzysztofkuczek/QCZEK_LRS#10]

**Comment by krzysztofkuczek** [comment]
Done

**Comment by brat002** [comment]
How to understand new fw naming?

**Comment by krzysztofkuczek** [comment]
Check readme.txt :)
Naming convention:
a) 1'st letter T - TX (master), R - RX (slave)
b) 3 letters for freqency, 433, 868 or 915
c) 1 letter for module power or type, A - 1W, B - 100mW
d) compiling flags
e) version
