### ISSUE TITLE
No S.Port telemetry data in 1.92

### ISSUE THREAD

**Issue by DiscoMan18** [krzysztofkuczek/QCZEK_LRS#15]
RSSI and SNR sensors are active and contain correct data. Values of other sensors are received by Taranis, but contain zeroes. Rediscovery of all sensors doesn't help.

**Comment by DiscoMan18** [comment]
Kris, have you managed to check it out?

**Comment by krzysztofkuczek** [comment]
yes it works fine...

**Comment by krzysztofkuczek** [comment]
@DiscoMan18 please let me know if you solve your problem

**Comment by DiscoMan18** [comment]
The problem solved. My fault - I flashed wrong version to the receiver ;)
