### ISSUE TITLE
AUX as third PWM output (e.g. flying wing need only 3 channels)

### ISSUE THREAD

**Issue by TomekFrs** [krzysztofkuczek/QCZEK_LRS#17]
M0 + M1 + AUX = 3 PWM channels

**Comment by TomekFrs** [comment]
M0 + M1 + AUX = 3 PWM channels

**Comment by krzysztofkuczek** [comment]
Hi @TomekFrs 
see description for:
noOfCPPMChnls – range 8-16. Number of CPPM channels. Starting from version 0.91 if it’s set to 0 on slave site, first channel value will be output as standard 50Hz servo PPM signal. It make possible to control single servo directly from receiver.
but please note that M0 and M1 are low quality PWM ...

**Comment by krzysztofkuczek** [comment]
feature are already implemented
