### ISSUE TITLE
Taranis X7: Telemetry lost / restored. Telemetry constantly falls off / on. Switch flight modes (CPPM + S.Port)

### ISSUE THREAD

**Issue by AlexeyII** [krzysztofkuczek/QCZEK_LRS#28]
There is also an audible warning: the engines disarmed / engines armed. Sounds are erroneous and do not affect the result. Also the mode switching in LUA to Taranis is not displayed correctly.

**Comment by AlexeyII** [comment]
Firmware:
T433A_P_CPPM_P_PXX_T_SPORT_V1.92.s19
R433A_T_MAVLINK_P_CPPM_P_SBUS_V1.92.s19

**Comment by AlexeyII** [comment]
For the test to be correct, I turned off the internal receiver(physically), there were no interference with the equipment.

**Comment by shaman7036** [comment]
A similar problem! in version 2.0 telemetry does not work normally!

**Comment by shaman7036** [comment]
A similar problem! in version 2.0 telemetry does not work normally! Moreover, in version 1.92 more or less something works! but also not without problems

**Comment by krzysztofkuczek** [comment]
Fixed in 2.10
