### ISSUE TITLE
ESP32 LoRa modules with custom firmware

### ISSUE THREAD

**Issue by ddosoff** [krzysztofkuczek/QCZEK_LRS#30]
Hello Krzysztof,

Is it possible to use FHSS with modules like https://heltec.org/project/wifi-lora-32/ ?

It is convenient that LoRa chip built in one module. I'd like to create something like 3dr radio from this boards.

**Comment by krzysztofkuczek** [comment]
I'm not going to migrate to esp32 platform. You can find other projects based on it.
