### ISSUE TITLE
Mavlink angle/heading

### ISSUE THREAD

**Issue by urlu75** [krzysztofkuczek/QCZEK_LRS#9]
The angle seems to be divided by 100 when sent through Mavlink.
[RCG link](https://www.rcgroups.com/forums/showpost.php?p=41007283&postcount=2683)

here is the result with a transparent serial link :
mavlink_msg_global_position_int_get_hdg : 11914
mavlink_msg_vfr_hud_get_heading : 11900

here is the the result with QLRS :
mavlink_msg_global_position_int_get_hdg : 116
mavlink_msg_vfr_hud_get_heading : 116

Heading with the serial transparent link is 100 times bigger .

**Comment by krzysztofkuczek** [comment]
hi @urlu75 ,
How did you get such a results?
I think that we have problem only with global possition.
Take a look at ardu plane raw data...
<img width="299" alt="mavlink1" src="https://user-images.githubusercontent.com/1246883/64271234-417a4e80-cf3d-11e9-9f83-f65769e581f7.PNG">

Kris

**Comment by urlu75** [comment]
edit, I misunderstood your message.
Yes I think the pb is only with global position, unit is cdeg (between 0.0 and 359,99)
var_hud unit is deg.

**Comment by krzysztofkuczek** [comment]
ok :)

**Comment by krzysztofkuczek** [comment]
Implemented.
